// <auto-generated />
namespace SMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SMSDBContext21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SMSDBContext21));
        
        string IMigrationMetadata.Id
        {
            get { return "201808120756315_SMSDBContext21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
