// <auto-generated />
namespace SMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SMSDBContext28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SMSDBContext28));
        
        string IMigrationMetadata.Id
        {
            get { return "201809221332572_SMSDBContext28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
